# Unidad 4 - Python NumPy

In [2]:
# Importamos la librería
import numpy as np
np.__version__

'1.18.2'

En `NumPy` el objeto básico se trata de una lista multidimensional de números normalmente del mismo tipo.

In [3]:
# Ejemplo de creación de un array
p = np.array([1, 2, 3])
p

array([1, 2, 3])

In [4]:
# De la misma forma que lo realizamos con list utilizamos los índices para extraer el valor
p[1]

2

In [5]:
# Analizamos el tipo de objeto
type(p)

numpy.ndarray

En *NumPy* , a las dimensiones se les conoce con el *nombre de ejes( axes )* y al *número de los ejes rango (rank)*.

Array es un alias para referirse al tipo de objeto *numpy.ndarray*

Tenemos algunas de las propiedades de los **arrays**
- *ndarray.ndim* : el número de ejes del objeto array (matriz)
- *ndarray.shape*: una tupla de números enteros indicando longitud de las dimensiones de la matriz
- *ndarray.size*: número total de elementos de una matriz

In [6]:
# Ejemplo de una matriz 3x2 (3 filas y 2 columnas)

a = np.arange(3*2) # con esta función creamos la estructura unidimensional de 6 elementos
print("Array unidimensional: ")
print(a)

Array unidimensional: 
[0 1 2 3 4 5]


In [7]:
# si quiero darle una forma de matriz 3x2 utilizo la función `reshape()`
a = a.reshape(3,2)
print("Matriz 3x2:")
print(a)

Matriz 3x2:
[[0 1]
 [2 3]
 [4 5]]


In [8]:
type(a)

numpy.ndarray

In [9]:
print(a[1]) # extraemos solo la segunda fila (posición 1 )
print(a[1,1]) # extraemos el valor de la segunda fila y segunda columna 

[2 3]
3


In [10]:
type(a[1]) # sigue siendo un array

numpy.ndarray

In [11]:
type(a[1,1]) # devuelve el tipo del valor extraido

numpy.int64

In [12]:
# dimensiones del array
a.ndim # devuelve el número de ejes

2

In [13]:
a.shape # longitud de las dimensiones

(3, 2)

In [14]:
a.size # el número de los elementos

6

A la hora de crear un array, tenemos diferentes opciones

In [15]:
# creamos un array de diez elementos
z = np.zeros(10) # utilizamos la función zeros para crear vectores de ceros.
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [16]:
type(z[1]) # el tipo será un float

numpy.float64

In [17]:
# podemos cambiar cualquiera de los valores accediendo por su posición
z[4] = 5. # es lo mismo que escribir 5.0
z[-1] = .1 # es lo mismo que 0.1
print(z) # nos devuelve un vector de float

[0.  0.  0.  0.  5.  0.  0.  0.  0.  0.1]


In [18]:
type(z)

numpy.ndarray

In [19]:
# cambiamos los valores de una matriz ya definida con range de numPy, `arange`, marcando el inicio y el fin
print(a)
a = np.arange(10,20) # incluimos el start 10 hasta 19
print(a)

[[0 1]
 [2 3]
 [4 5]]
[10 11 12 13 14 15 16 17 18 19]


In [20]:
type(a)

numpy.ndarray

In [21]:
# también podemos incluir los pasos, step
a = np.arange(10,20,2)
print(a)

[10 12 14 16 18]


In [22]:
a

array([10, 12, 14, 16, 18])

In [23]:
# Podemos crear arrays desde listas de Python de varias dimensiones
a = np.array([[1,2,3], [4,5,6]])
print(a)


[[1 2 3]
 [4 5 6]]


## Operaciones con matrices

Con `numPy` podemos implementar todas las operaciones habituales con matrices

In [24]:
# construimos dos matrices
A = np.array([[1,0],[0,1]])
B = np.array([[1,2],[3,4]])
C = np.array([[1,5],[6,4],[8,9]])
print(A)
print("*"*50)
print(B)
print("*"*50)
print(C)

[[1 0]
 [0 1]]
**************************************************
[[1 2]
 [3 4]]
**************************************************
[[1 5]
 [6 4]
 [8 9]]


In [25]:
# suma de matrices
print(A+B)

[[2 2]
 [3 5]]


In [26]:
print(A+C) # devolverá un error de valor por no tener el mismo `shape` 

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [27]:
# Resta de matrices
print(A-B)

[[ 0 -2]
 [-3 -3]]


In [28]:
# multiplicación de matrices por elemento y elemento
print(A*B)

[[1 0]
 [0 4]]


In [29]:
# multiplicación matriz por otra matriz
print(A.dot(B))

[[1 2]
 [3 4]]


In [30]:
# Potencia
print(B**2)

[[ 1  4]
 [ 9 16]]


## Slicing e Iteración

los arrays de Numpy soportan la técnica de *slicing* de Python.

In [31]:
# creamos un array de 0 a 9
b = np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [33]:
# Obtenemos los elementos de la posición 3 del array
print(b[2:5]) # siempre inicio y final -1

[2 3 4]


In [34]:
# todos los elementos de la tercera posición en adelante
print(b[2:])

[2 3 4 5 6 7 8 9]


In [35]:
# Si queremos iterar por cada elemento
for i in b:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [36]:
# creamos un array multidimensional
C = np.arange(18).reshape(6,3)
print(C)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [38]:
# Accedemos a la posición 4a fila y 3a columna
print(C[3][2])

# accedemos la posición 4a fila y 3a columna de forma alternativa
print(C[3, 2])

11
11


In [45]:
print(C[2]) # accedemos a la fila completa

[6 7 8]


In [46]:
# accedemos a la columna completa
print(C[:,0]) # accedemos a la columna 1

[ 0  3  6  9 12 15]


In [47]:
# Extraemos todas las filas hasta la 5a fila
print(C[:5])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [51]:
# vamos a iterar en un array multidimensional
for i in range(C.shape[0]):
    for j in range(C.shape[1]):
        print("Elemento: {}".format(C[i , j]))

Elemento: 0
Elemento: 1
Elemento: 2
Elemento: 3
Elemento: 4
Elemento: 5
Elemento: 6
Elemento: 7
Elemento: 8
Elemento: 9
Elemento: 10
Elemento: 11
Elemento: 12
Elemento: 13
Elemento: 14
Elemento: 15
Elemento: 16
Elemento: 17


In [52]:
# slicing en asignaciones
C[3,2] = 42
print(C)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 42]
 [12 13 14]
 [15 16 17]]


In [53]:
# realizamos el cambio en bloque como una fila completa
C[2] = [666, 666, 666]
print(C)

[[  0   1   2]
 [  3   4   5]
 [666 666 666]
 [  9  10  42]
 [ 12  13  14]
 [ 15  16  17]]


In [54]:
# cambio de todos los valores por N utilizamos (...)
D = C # realizo un backup
D[...] = 0 # asigno a todos los valores el cero
print(D)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


## Conway's Game of Life

referencia: [Wikipedia](https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life)

In [77]:
SIZE = 10
STEPS = 10

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

# Creamos un tablero con células vivas o muertas de forma aleatoria.
Z = np.random.randint(0,2,(SIZE, SIZE))
# Simulamos durante los pasos indicados.
for i in range(STEPS):
    Z = iterate(Z)
# Mostramos el tablero en el paso final.
print(Z)
    

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
