# Unidad 4 - Python NumPy

In [2]:
# Importamos la librería
import numpy as np
np.__version__

'1.18.2'

En `NumPy` el objeto básico se trata de una lista multidimensional de números normalmente del mismo tipo.

In [5]:
# Ejemplo de creación de un array
p = np.array([1, 2, 3])
p

array([1, 2, 3])

In [7]:
# De la misma forma que lo realizamos con list utilizamos los índices para extraer el valor
p[1]

2

In [9]:
# Analizamos el tipo de objeto
type(p)

numpy.ndarray

En *NumPy* , a las dimensiones se les conoce con el *nombre de ejes( axes )* y al *número de los ejes rango (rank)*.

Array es un alias para referirse al tipo de objeto *numpy.ndarray*

Tenemos algunas de las propiedades de los **arrays**
- *ndarray.ndim* : el número de ejes del objeto array (matriz)
- *ndarray.shape*: una tupla de números enteros indicando longitud de las dimensiones de la matriz
- *ndarray.size*: número total de elementos de una matriz

In [10]:
# Ejemplo de una matriz 3x2 (3 filas y 2 columnas)

a = np.arange(3*2) # con esta función creamos la estructura unidimensional de 6 elementos
print("Array unidimensional: ")
print(a)

Array unidimensional: 
[0 1 2 3 4 5]


In [11]:
# si quiero darle una forma de matriz 3x2 utilizo la función `reshape()`
a = a.reshape(3,2)
print("Matriz 3x2:")
print(a)

Matriz 3x2:
[[0 1]
 [2 3]
 [4 5]]


In [13]:
type(a)

numpy.ndarray

In [18]:
print(a[1]) # extraemos solo la segunda fila (posición 1 )
print(a[1,1]) # extraemos el valor de la segunda fila y segunda columna 

[2 3]
3


In [22]:
type(a[1]) # sigue siendo un array

numpy.ndarray

In [24]:
type(a[1,1]) # devuelve el tipo del valor extraido

numpy.int64

In [26]:
# dimensiones del array
a.ndim # devuelve el número de ejes

2

In [28]:
a.shape # longitud de las dimensiones

(3, 2)

In [29]:
a.size # el número de los elementos

6

A la hora de crear un array, tenemos diferentes opciones

In [30]:
# creamos un array de diez elementos
z = np.zeros(10) # utilizamos la función zeros para crear vectores de ceros.
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [32]:
type(z[1]) # el tipo será un float

numpy.float64

In [33]:
# podemos cambiar cualquiera de los valores accediendo por su posición
z[4] = 5. # es lo mismo que escribir 5.0
z[-1] = .1 # es lo mismo que 0.1
print(z) # nos devuelve un vector de float

[0.  0.  0.  0.  5.  0.  0.  0.  0.  0.1]


In [39]:
type(z)

numpy.ndarray

In [42]:
# cambiamos los valores de una matriz ya definida con range de numPy, `arange`, marcando el inicio y el fin
print(a)
a = np.arange(10,20) # incluimos el start 10 hasta 19
print(a)

[[0 1]
 [2 3]
 [4 5]]
[10 11 12 13 14 15 16 17 18 19]


In [43]:
type(a)

numpy.ndarray

In [44]:
# también podemos incluir los pasos, step
a = np.arange(10,20,2)
print(a)

[10 12 14 16 18]


In [45]:
a

array([10, 12, 14, 16, 18])

In [46]:
# Podemos crear arrays desde listas de Python de varias dimensiones
a = np.array([[1,2,3], [4,5,6]])
print(a)


[[1 2 3]
 [4 5 6]]


## Operaciones con matrices

Con `numPy` podemos implementar todas las operaciones habituales con matrices

In [53]:
# construimos dos matrices
A = np.array([[1,0],[0,1]])
B = np.array([[1,2],[3,4]])
C = np.array([[1,5],[6,4],[8,9]])
print(A)
print("*"*50)
print(B)
print("*"*50)
print(C)

[[1 0]
 [0 1]]
**************************************************
[[1 2]
 [3 4]]
**************************************************
[[1 5]
 [6 4]
 [8 9]]


In [48]:
# suma de matrices
print(A+B)

[[2 2]
 [3 5]]


In [55]:
print(A+C) # devolverá un error de valor por no tener el mismo `shape` 

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [56]:
# Resta de matrices
print(A-B)

[[ 0 -2]
 [-3 -3]]


In [57]:
# multiplicación de matrices por elemento y elemento
print(A*B)

[[1 0]
 [0 4]]


In [58]:
# multiplicación matriz por otra matriz
print(A.dot(B))

[[1 2]
 [3 4]]


In [59]:
# Potencia
print(B**2)

[[ 1  4]
 [ 9 16]]
