# Programación 201

Librerías científicas en Python: `NumPy`
------------------------------------------------------

### Ejercicio 1
Calculad la norma y el determinante de la siguiente matriz: ```[[1, 0], [2, -1]]```.

In [2]:
# Importamos la librería Numpy

import numpy as np

np.__version__

'1.18.5'

In [12]:
# Respuesta

a = ([[1, 0], [2, -1]])

determinante = np.linalg.det(a)
norma = np.linalg.norm(a)

print(determinante)
print(norma)


-1.0
2.449489742783178


### Ejercicio 2 
Evaluad las funciones arcoseno y arcocoseno en el intervalo [0,1] y con paso (resolución) de 0.1 y guardadlas en dos _arrays_.

In [47]:
# Respuesta

# Primero creamos un array en el intervalo [0,1] y con paso de 0.1
b = np.arange(0,1.0,0.1)
print(b)

# Compruebo el tipo y el número de elementos
print(type(b))
print(b.size)

# Después calculamos el arcoseno y el arcocoseno del array creado
arcosenos = np.arcsin(b)
print(arcosenos)

arcocosenos = np.arccos(b)
print(arcocosenos)


[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
<class 'numpy.ndarray'>
10
[0.         0.10016742 0.20135792 0.30469265 0.41151685 0.52359878
 0.64350111 0.7753975  0.92729522 1.11976951]
[1.57079633 1.47062891 1.36943841 1.26610367 1.15927948 1.04719755
 0.92729522 0.79539883 0.64350111 0.45102681]


### Ejercicio 3
Generad una lista de 100 valores enteros aleatorios de 0-9. Realizad los siguientes cálculos utilizando métodos de _numpy_:
- Media y desviación estándar de los valores de la lista
- Valor máximo y mínimo
- Sumad todos los valores de la lista
- Conseguid una lista de valores únicos

In [10]:
# Respuesta

# Generamos la lista de 100 valores enteros aleatorios
# Creamos una lista "vacía"
valores_aleatorios = []

# Untilizamos un bucle for...loop para ir añadiendo valores enteros (función 'randint') a la lista de forma aleatoria (función 'random')
for i in range(100):
    x = np.random.randint(10)
    valores_aleatorios.append(x)

# Imprimimos la lista por pantalla para comprobar que es correcta
# print(valores_aleatorios)

# Convertimos la lista en un array para poder operar con ella
valores_aleatorios = np.array(valores_aleatorios)

# Media y y desviación estándar de los valores de la lista
media = valores_aleatorios.mean()
print(f'La media de los valores de la lista es: {media}')

desviacion_estandar = valores_aleatorios.std()
print(f'La desviación estándar de los valores de la lista es: {desviacion_estandar}')

# Valor máximo y mínimo de los valores de la lista
valor_maximo = valores_aleatorios.max()
print(f'El valor máximo de los valores de la lista es: {valor_maximo}')

valor_minimo = valores_aleatorios.min()
print(f'El valor mínimo de los valores de la lista es: {valor_minimo}')
# Era previsible que estos fuesen los valores máximo y mínimo de la lista al haber generado un listado de valores aleatorios precisamente entre 0 y 9

# Sumamos los valores de la lista:
suma_valores = valores_aleatorios.sum()
print(f'La suma de los valores de la lista es: {suma_valores}')

# Lista de valores únicos
valores_unicos = np.unique(valores_aleatorios)
print(f'La lista de los valores únicos de la lista es: {valores_unicos}')


La media de los valores de la lista es: 4.75
La desviación estándar de los valores de la lista es: 2.9878922336657325
El valor máximo de los valores de la lista es: 9
El valor mínimo de los valores de la lista es: 0
La suma de los valores de la lista es: 475
La lista de los valores únicos de la lista es: [0 1 2 3 4 5 6 7 8 9]


### Ejercicio 4
Ordenad la matriz bidimensional ```[[5,1,7], [0,7,4], [7,23,1]]``` por filas utilizando como algoritmo de ordenación el [Merge sort](https://en.wikipedia.org/wiki/Merge_sort).

**Hint:** No es necesario que implementéis el algoritmo de ordenación a mano, NumPy contiene métodos para realizar diferentes tipos de ordenación sobre diferentes estructuras de datos.

In [87]:
# Respuesta
# Definimos la matriz
c = [[5,1,7], [0,7,4], [7,23,1]]

# Ordenamos la matriz por el método 'mergesort' de numpy
c_ordenada = np.sort(c, kind = 'mergesort')

# Mostramos el resultado por pantalla
print(c_ordenada)


[[ 1  5  7]
 [ 0  4  7]
 [ 1  7 23]]


### Ejercicio 5
Definid una función que dadas dos matrices, devuelva el valor absoluto de la multiplicación de los determinantes ambas, es decir, dadas A y B, nuestra función devolverá `|det(A) * det(B)|`.

In [17]:
# Respuesta

# Definimos la función apoyándonos en el cálculo del determinante de una matriz visto en puntos anteriores y en la función 'np.abs' que nos devuelve el valor absoluto
def multiplicar_determinantes (A,B):
    return np.abs(np.linalg.det(A) * np.linalg.det(B))

# Para comprobar la nueva función, definimos dos matrices
A = ([[1, 0], [2, -1]])
B = ([[1, 0], [2, 1]])  

print(np.linalg.det(A))
print(np.linalg.det(B))
print (f'El valor absoluto de la multiplicación de los determinantes de las matrices A y B es: {multiplicar_determinantes(A, B)}')

# El valor de multiplicar los determinantes de ambas matrices sería -1 que, en valor absoluto, nos devuelve el valor 1.


-1.0
1.0
El valor absoluto de la multiplicación de los determinantes de las matrices A y B es: 1.0


### Ejercicio 6
Cread una matriz 10x10 que corresponda con la [matriz identidad](https://es.wikipedia.org/wiki/Matriz_identidad) usando generadores básicos de arrays. Cread una matriz identidad 10x10 (esta vez usando generadores especificos de matrices identidad) y comprobad que ambas matrices son iguales

**Consideraciones**:
- La primera matriz debe crearse usando constructores básicos de arrays, como los presentados en los Notebooks de teoría.
* La segunda matriz debe generarse utilizando el generador de matrices identidad de numpy.
* La comparación debe devolver True si las matrices son iguales (un único True), False de no ser así.

In [24]:
# Respuesta

# Generamos la primera matriz identidad mediante generadores básicos de arrays:
# Creamos la matriz de 100 valores, todos ellos igual a cero
i_1 = np.zeros(100)

# Generamos el rango necesario para iterar en el momento de cambiar los ceros por unos
rango = np.arange(0, 100, 11)

# Utilizamos un bucle for para la sustitución de valores
for i in rango:
    i_1[i]=1

# Damos la forma 10 x 10 a la matriz identidad generada
i_1 = i_1.reshape(10, 10)
# print(i_1)

# Generamos la segunda matriz mediante el generador de matrices identidad de numpy
i_2 = np.identity(10)
# print(i_2)

# Comparamos las dos matrices generadas para ver si son iguales:
(i_1 == i_2).all()


True

### Ejercicio 7
Cread una matriz de 2x6 donde los valores de cada posición `(i, j)` correspondan a `i^2+j` para todo `i` par, `i/j^2` para todo `i` impar.

In [49]:
# Respuesta

# Creamos la matriz 2x6
d = np.arange(2*6).reshape(2,6)

# Iteramos con un for...loop por la matriz creada y sustituimos los valores por las formaulas definidas en el enunciado, dependiendo de si la i es par (0) o impar (1)
for i in range(2):
    for j in range(6):
        if i == 0:
            d[i,j] = (i+1)**2+(j+1)
        else:
            d[i,j] = (i+1)/((j+1)**2)

# Imprimimos por pantalla en valor resultante de la matriz
print(d)


[[2 3 4 5 6 7]
 [2 0 0 0 0 0]]


array([[2, 3, 4, 5, 6, 7],
       [2, 0, 0, 0, 0, 0]])

### Ejercicio 8
Cread dos matrices de tamaño 5x5 con números reales aleatorios. Obtened el resultado de multiplicar ambas matrices usando los dos métodos de multiplicación de matrices vistos en el Notebook de teoría. ¿Cuál es la diferencia entre ambos resultados? Cread ahora dos matrices de tamaño 4x5 y 5x5 respectivamente, repetid la operación. Describid cuál de los métodos de multiplicación podéis aplicar y porqué

In [79]:
# Respuesta
# Generamos dos matrices de tamaño 5x5 con números reales aleatorios
e = np.random.rand(5,5)
f = np.random.rand(5,5)

# Multiplicamos las dos matrices usando los dos métodos de multiplicación de matrices vistos en clase
print (e*f)
print(e.dot(f))

# Generamos dos nuevas matrices de tamaño 4x5 y 5x5, respectivamente

g = np.random.rand(4,5)
h = np.random.rand(5,5)

# Repetimos las operaciones anteriores
# print (g*h)
print(g.dot(h))

# En este caso, hemos tenido que comentar el primero de los métoodos de multiplicación puesto que daba un error al tratarse de dos matrices de distinto tamaño. 
""" ValueError: operands could not be broadcast together with shapes (4,5) (5,5) """
# Por tanto, solamente sería posible aplicar el método de multimplicación '.dot()' en el caso de matrices de tamaños distintos


[[0.27422595 0.16996484 0.03536164 0.04245432 0.17599313]
 [0.01109138 0.27138079 0.04780355 0.30560435 0.48821499]
 [0.24755448 0.26990346 0.24031011 0.42665582 0.00670654]
 [0.06247974 0.05813091 0.34013729 0.14648474 0.17360118]
 [0.25665975 0.30977941 0.42776434 0.05033676 0.17650564]]
[[0.82658024 0.84095098 0.61977081 0.59630165 0.52039231]
 [0.60147924 0.80639397 0.93308458 0.61222057 0.70896116]
 [0.93935021 1.01713154 1.03476434 1.13201562 0.75646019]
 [2.17965187 2.3749684  1.76559971 1.60866978 1.58689639]
 [1.39945861 1.41316061 1.22183124 1.29251653 0.9115786 ]]
[[0.91780754 0.52400388 0.09657099 0.73240481 0.29624951]
 [1.5281508  0.73056351 0.43742237 1.02384626 0.43487271]
 [2.14943215 1.48740208 0.56030481 1.90505601 0.8198586 ]
 [2.55580968 1.3733773  0.68731022 2.00792158 0.86574521]]


' ValueError: operands could not be broadcast together with shapes (4,5) (5,5) '